# Generated by Django 5.0.6 on 2024-07-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_total_sum_payment_payment_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_sum',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_link',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='payment',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID сессии'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='card', max_length=20, verbose_name='способ оплаты'),
        ),
    ]
